// Generated by LiveScript 1.6.0
(function(){
  var kindlegen, expect, path, fs, It;
  kindlegen = require('../');
  expect = require('chai').expect;
  path = require('path');
  fs = require('fs');
  It = global.it;
  describe('Basic Usage', function(){
    var epub;
    this.timeout(10000);
    epub = null;
    before(function(done){
      return fs.readFile(path.resolve(__dirname, 'test.epub'), function(error, data){
        if (error) {
          return done(error);
        }
        epub = data;
        return done();
      });
    });
    return It('should properly convert epub buffer', function(done){
      return kindlegen(epub, function(error, mobi){
        expect(error).to.be['null'];
        expect(mobi).to.exist;
        expect(Buffer.isBuffer(mobi)).to.be['true'];
        expect(mobi).to.have.length.above(5000);
        return done();
      });
    });
  });
}).call(this);
